### PR TITLE
fix: show sarif output

### PR DESCRIPTION
**Pull request by georgismitev**

### CODE REVIEW

**Comment by prabhu** [comment]
Hi @georgismitev 

I saw this sarif related error and have pushed out a fix for ShiftLeft Scan. Please Re-run the action workflow and it should work fine now.

**Comment by georgismitev** [comment]
@prabhu thanks, looks like it is fixed. 

Just out of curiosity, how do you analyse the prs (the diff itself)?

**Comment by prabhu** [comment]
I can see some warnings under Checks -> Code Scanning -> ShiftLeft *. Are you asking how we have implemented this? Will you be able to email me so that I can answer your questions better? prabhu@shiftleft.io

**Comment by georgismitev** [comment]
@prabhu ah, sure, my goal wasn't fixing the found issues, but the action itself.

**Pull request closed without merging**
